name: predixcan_prediction
channels:
  - defaults
dependencies:
  - gcc_linux-64=7.3.0
  - h5py=2.9.0
  - ipython=7.2.0
  - numpy=1.15.4
  - pandas=0.23.4
  - python=3.7.2
  - r-base=3.5.0
  - r-rcpp=0.12.16
  - rpy2=2.9.1
  - scipy=1.1.0
  - tqdm=4.28.1
  - pip:
    - h5py-cache==1.0
