name: predixcan_predictions
channels:
  - conda-forge
  - defaults
dependencies:
  - bgen=2.1.0
  - cffi=1.11
  - dask=1.0
  - h5py=2.9
  - ipython=7.2
  - numpy=1.15
  - pandas=0.23
  - pytest=4.0
  - python=3.7
  - scipy=1.2
  - tqdm=4.28
  - xarray=0.11
  - pip:
    - bgen-reader==2.0.8
    - h5py-cache==1.0.0
